---
- name: Deploy To INTE-Windows-VM
  hosts: "{{inventory_group_of_hosts}}"

  #ToDo
  #  vars:
  #    local_app_path: "C:\\Tools\\fos-worker"
  #    java_path: "C:\\Tools\\jdk-17.0.1\\bin\\java.exe"
  #    log_directory_path: "{{local_app_path}}\\log"

  tasks:
    - name: Test Connectivity
      win_ping:

    #ToDo: Create directory if not present
    #    - name: Create directory if not present
    #      win_file: path={{local_app_path}} state=directory

    #ToDo: Install nssm (non-sucking service manager) via chocolatey
    #    - name: Install nssm (non-sucking service manager) via chocolatey
    #      win_chocolatey:
    #        name: nssm

    #ToDo: copy certificates and private keys

    - name: Copy JAR From Runner To App-Directory Of Remote Machine
      win_copy:
        src: "{{jar_source_path}}"
        dest: "{{local_app_path}}\\{{windows_service_name}}-{{artifact_version}}.jar"
        remote_src: false

    - name: Stop Windows Service
      win_service:
        name: "{{windows_service_name}}"
        state: stopped

    - name: Keep Old JAR
      win_copy:
        src: "{{local_app_path}}\\{{target_jar_name}}"
        dest: "{{local_app_path}}\\old_jar_that_ran_before.jar"
        remote_src: true

    - name: Rename New JAR To Name That Gets Executed By NSSM
      win_copy:
        src: "{{local_app_path}}\\{{windows_service_name}}-{{artifact_version}}.jar"
        dest: "{{local_app_path}}\\{{target_jar_name}}"
        remote_src: true


    #ToDo Install Spring Boot app as Windows service (via nssm), if not already there - but remain stopped to configure Application directory
    #    - name: Install Spring Boot app as Windows service (via nssm), if not already there - but remain stopped to configure Application directory
    #      win_nssm:
    #        name: "{{windows_service_name}}"
    #        application: "{{java_path}}"
    #        arguments: -Djavax.net.ssl.trustStore=cacerts -Djavax.net.ssl.trustStorePassword=changeit -Dhttp.proxyHost=gateway.zscloud.net -Dhttps.proxyHost=gateway.zscloud.net -Dhttp.proxyPort=10268 -Dhttps.proxyPort=10268 -Dhttp.nonProxyHosts=*.media.int -Dhttps.nonProxyHosts=*.media.int -jar -Dspring.profiles.active=test fileoperation.worker.j>#        stdout_file: "{{log_directory_path}}\\stdout.log"
    #        stderr_file: "{{log_directory_path}}\\stderr.log"
    #        state: stopped
    #
    #    - name: Set the Application path for the Spring Boot app
    #      raw: nssm set {{windows_service_name}} AppDirectory {{local_app_path}}

    - name: Fire Up Windows Service
      win_service:
        name: "{{windows_service_name}}"
        state: restarted

    - name: Wait Until App Is UP & RUNNING
      win_uri:
        url: "http://localhost:8080/actuator/health"
        method: GET
      register: result
      until: result.status_code is defined and result.status_code == 200
      retries: 5
      delay: 5