name: Release
run-name: Release ${{ inputs.version }} on ${{ inputs.environment }}

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment environment'
        type: string
        default: test
      version:
        description: 'Release version'
        type: string
        required: true
      deploymentNamespace:
        type: string
      deploymentManifestsDirectory:
        type: string
        default: "./deployment"
    secrets:
      INTE_CARGO_URL:
        required: true
      INTE_CARGO_SECRET:
        required: true
jobs:
  deploy-to-cluster:
    runs-on: srf-inte-cargo
    timeout-minutes: 10

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Set environment specific variables
        run: |
          if [ "test" == "${{ inputs.environment }}" ]
          then
            echo "inte-domain=inte-test.media.int" >> $GITHUB_ENV
          elif [ "prod" == "${{ inputs.environment }}" ]
          then
            echo "inte-domain=inte.media.int" >> $GITHUB_ENV
          else
            echo "Error: Unknown environment"
            exit 1
          fi

      - name: Replace token in manifest
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["${{ inputs.deploymentManifestsDirectory }}/*.yaml", "${{ inputs.deploymentManifestsDirectory }}/*.yml", "./kustomize/*.yaml"]'
        env:
          environment: ${{ inputs.environment }}
          version: ${{ inputs.version }}

      - name: Login to cluster with service-account
        uses: azure/k8s-set-context@v3
        with:
          method: service-account
          k8s-url: ${{ secrets.INTE_CARGO_URL }}
          k8s-secret: ${{ secrets.INTE_CARGO_SECRET }}

      - name: Deploy app to cluster
        env:
          DEPLOYMENT_NAMESPACE: ${{ inputs.deploymentNamespace }}
          DEPLOYMENT_MANIFEST_DIRECTORY: ${{ inputs.deploymentManifestsDirectory }}
        run: |
          kubectl version
          kubectl -n inte-angebot get pods
          env | sort
          if [[ $DEPLOYMENT_NAMESPACE ]]
          then
            echo "Update K8s resources in namespace $DEPLOYMENT_NAMESPACE"
            deployment_name=$(kubectl -n $DEPLOYMENT_NAMESPACE apply -f $DEPLOYMENT_MANIFEST_DIRECTORY -ojson | jq -r '.items[] | select(.kind == "Deployment") | .metadata.name')
            echo "Wait until deployment $deployment_name in namespace $DEPLOYMENT_NAMESPACE finishes"
            kubectl -n $DEPLOYMENT_NAMESPACE rollout status Deployment/$deployment_name 
          else
            echo "Deploy with kustomize the following resources"
            kubectl diff -k ./kustomize || true
            deployments=$(kubectl apply -k ./kustomize -ojson | jq -r '.items[] | select(.kind == "Deployment") | "\(.metadata.namespace),\(.metadata.name)"')
            for deployment in $deployments ; do
              ns=$( echo "$deployment" | cut -f1 -d ',')
              deployment_name=$( echo "$deployment" | cut -f2 -d ',')
              echo "Wait until deployment $deployment_name in namespace $ns finishes"
              kubectl -n $ns rollout status Deployment/$deployment_name
            done
          fi
        
