name: Build & Test Gradle project

on:
  workflow_call:
    inputs:
      publishJar:
        type: boolean
        default: false
      createContainer:
        type: boolean
        default: false
      skipJacocoReport:
        type: boolean
        default: false
      javaVersion:
        type: number
        default: 17
      gradleBuildTasks:
        type: string
        default: "clean build test jacocoTestReport --info"
      gradleBuildTasksSkipCoverage:
        type: string
        default: "clean build test --info"
      gradlePublishJarTasks:
        type: string
        default: "publish"
      gradleDockerTasks:
        type: string
        default: "dockerPush"

jobs:
  gradle-build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INTE_JFROG_ARTIFACT_TOKEN: ${{ secrets.INTE_JFROG_ARTIFACT_TOKEN }}
      AZURE_ARTIFACTS_ENV_ACCESS_TOKEN: ${{ secrets.INTE_AZURE_ARTIFACT_TOKEN }}

    steps:
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ inputs.javaVersion }}
    - name: Setup gradle
      uses: gradle/gradle-build-action@v2

    - name: Checkout project sources
      uses: actions/checkout@v3

    - name: Build, test & code coverage
      if: inputs.skipJacocoReport == false
      run: ./gradlew ${{ inputs.gradleBuildTasks }}
    - name: Build, test without code coverage
      if: inputs.skipJacocoReport == true
      run: ./gradlew ${{ inputs.gradleBuildTasksSkipCoverage }}

    - name: Sonar (with test coverage)
      if: inputs.skipJacocoReport == false
      run: ./gradlew sonar -Pcoverage
      permissions:
        pull-requests: read
      env:
        SONAR_TOKEN: ${{ secrets.INTE_SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Sonar (without test coverage)
      if: inputs.skipJacocoReport == true
      run: ./gradlew sonar
      permissions:
        pull-requests: read
      env:
        SONAR_TOKEN: ${{ secrets.INTE_SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #- name: SonarQube Scan
    #  uses: sonarsource/sonarqube-scan-action@master
    #  env:
    #    SONAR_HOST_URL: https://sonarcloud.io
    #    SONAR_TOKEN: ${{ secrets.INTE_SONAR_TOKEN }}

    - name: Publish jar
      if: startsWith(github.ref, 'refs/tags/') && inputs.publishJar
      run: ./gradlew ${{ inputs.gradlePublishJarTasks }}

    - name: Login to STXT Registry
      if: startsWith(github.ref, 'refs/tags/') && inputs.createContainer
      uses: docker/login-action@v2
      with:
        registry: registry.swisstxt.ch
        username: ${{ secrets.INTE_STXT_REGISTRY_USERNAME }}
        password: ${{ secrets.INTE_STXT_REGISTRY_TOKEN }}

    - name: Create docker container
      if: startsWith(github.ref, 'refs/tags/') && inputs.createContainer
      run: ./gradlew ${{ inputs.gradleDockerTasks }}
